package-lock.json
package.json

Update loopback dependencies to latest

Update to latest loopback packages

---

package-lock.json
package.json

Updated `@types/express` as required by `@loopback/express`

bug fixes for npm test

---

README.md

Added references and use case of the RevokedTokenRepository in the httpBearer stategy.
Fixes #19

docs(http-bearer): added revokedtokenrepository reference

---

.cz-config.js
.eslintignore
.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
DEVELOPING.md
commitlint.config.js
package-lock.json
package.json

 feat(ci-cd): commitizen added

---

.eslintignore
.github/PULL_REQUEST_TEMPLATE.md
.nycrc
package.json
src/__tests__/integration/passport-apple-oauth2/apple-oauth2.integration.ts
src/__tests__/integration/passport-keycloak/keycloak.integration.ts
src/__tests__/unit/passport-apple-oauth2/apple-auth-strategy.unit.ts
src/__tests__/unit/passport-keycloak-oauth2/keycloak-auth-strategy.unit.ts
src/__tests__/unit/passport-keycloak-oauth2/keycloak-user-profile.unit.ts
src/strategies/passport/passport-keycloak/keycloak-strategy-factory-provider.ts
src/strategies/passport/passport-keycloak/keycloak-verify.provider.ts
src/strategies/types/index.ts
src/strategies/types/keycloak.types.ts
src/strategies/types/types.ts
src/strategies/user-auth-strategy.provider.ts

Added tests for apple and keycloak, added types missing from [this PR](https://github.com/sourcefuse/loopback4-authentication/pull/20). increased coverage.
Fixes #49 

test(core): add test for some providers, increase coverage

---

package-lock.json
package.json

GH-0
Updated lb4 authentication peer dependencies.

fix(chore): update lb4 authentication peer dependencies

---

src/error-keys.ts
src/strategies/passport/passport-otp/otp-auth.ts

minor fix in OTP strategy, and added few error keys
Fixes #69 

fix(provider): minor fix in otp strategy

---

src/error-keys.ts
src/types.ts

added mfa property to ClientAuthCode interface
Fixes # (issue)

refactor(component): add mfa property to ClientAuthCode interface

---

package.json

GH-85
When dependencies are updated using chore as the type a patch version will be released
Fixes #85 

chore(deps): semantic release

---

package-lock.json
package.json

GH-88
Fix vulnerability
Fixes # (issue)

chore(deps): fix vulnerability

---

package-lock.json
package.json
src/middlewares/client-authentication.middleware.ts
src/middlewares/user-authentication.middleware.ts

- moved duplicate code block from action and middleware providers to a new helper provider.
- removed overrides
Fixes #105 

refactor(provider): remove duplicate code block from action and middleware providers

---

src/keys.ts
src/types.ts

added new binding for User model.
Fixes #107 

feat(component): add new binding for User model

---

package-lock.json
package.json

GH-103
Updated the peer dependencies
Fixes #103

chore(deps): update the peer as well

---

.cz-config.js
commitlint.config.js
package-lock.json
package.json
src/release_notes/mymarkdown.ejs
src/release_notes/post-processing.js
src/release_notes/release-notes.js

Using Customizable npm package to generate changelog
updated loopback packages
GH-121
Using Customizable npm package to generate changelog
The changelog will be more detailed
Updated all the packages to latest using loopback cli
Fixes #121 

feat(core): generate detailed and informative changelog

---

package.json

When the package is intsalled
vendor folder should be a part of it
GH-135
Fixes #135 

fix(component): include vendor files in package.json

---

package-lock.json
package.json

remove all current vilnenrability of loopback4-authentication
GH-140
Fixes #140 

remove all current vilnenrability of loopback4-authentication

---

.cz-config.js
package-lock.json
src/release_notes/post-processing.js

now will show correct issue description as well
GH-138
corrected the issue number
now will show correct issue description as well
Fixes #138 

fix(chore): corrected the issue number

---

README.md
src/strategies/SAML/saml-strategy-factory-provider.ts

changed order for constructor arguments in saml
GH-177
changed order for constructor arguments in saml
Fixes #177 

fix(provider): change order for constructor arguments in saml

---

.github/workflows/release.yaml

release will be via the workflow
BREAKING CHANGE:
remove support for node 16
GH-192
add a release github action
Fixes #192 

feat(ci-cd): add a release github action

---

package-lock.json
src/strategies/passport/passport-client-password/client-password-strategy-factory-provider.ts
src/strategies/passport/passport-client-password/secure-client-password-strategy-factory-provider.ts

remove the unused ignore statement for eslint
GH-194
fix the eslint errors
Fixes #194 
Run the npm run eslint command locally

fix(chore): fix the eslint errors

---

catalog-info.yaml
docs/index.md
mkdocs.yml

techdocs backstgae

---

docs/README.md

badges will be visible on the package
GH-203
added synk and sonar badges
Fixes #203 

docs(chore): add synk and sonar badges

---

src/__tests__/fixtures/providers/azuread-auth.provider.ts
src/strategies/client-auth-strategy.provider.ts
src/strategies/passport/passport-apple-oauth2/apple-auth-strategy-factory-provider.ts
src/strategies/passport/passport-azure-ad/azuread-auth-verify.provider.ts
src/strategies/passport/passport-bearer/bearer-token-verify.provider.ts
src/strategies/passport/passport-client-password/client-password-verify.provider.ts
src/strategies/passport/passport-cognito-oauth2/cognito-auth-verify.provider.ts
src/strategies/passport/passport-facebook-oauth2/facebook-auth-strategy-factory-provider.ts
src/strategies/passport/passport-facebook-oauth2/facebook-auth-verify.provider.ts
src/strategies/passport/passport-google-oauth2/google-auth-strategy-factory-provider.ts
src/strategies/passport/passport-google-oauth2/google-auth-verify.provider.ts
src/strategies/passport/passport-insta-oauth2/insta-auth-strategy-factory-provider.ts
src/strategies/passport/passport-insta-oauth2/insta-auth-verify.provider.ts
src/strategies/passport/passport-keycloak/keycloak-verify.provider.ts
src/strategies/passport/passport-local/local-password-verify.provider.ts
src/strategies/passport/passport-otp/otp-auth.ts
src/strategies/passport/passport-otp/otp-verify.provider.ts
src/strategies/passport/passport-resource-owner-password/resource-owner-strategy-factory-provider.ts
src/strategies/passport/passport-resource-owner-password/resource-owner-verify.provider.ts
src/strategies/user-auth-strategy.provider.ts
src/types.ts

fix sonar code smells related to function type,
any typings and empty constructors
GH-204
Fixes #204 

refactor(chore): fix sonar code smells

---

package-lock.json
package.json
src/strategies/passport/passport-otp/otp-auth.ts

loopback version updates
GH-211
loopback version updates
Fixes #211 

chore(deps): loopback version updates

---

.github/workflows/sync-docs.yaml
package-lock.json

change the readme path for sync docs action
GH-206
change the readme path for sync docs action
Fixes #206

chore(ci-cd): update readme path in sync docs action

---

package.json
src/index.ts
src/strategies/passport/index.ts
src/strategies/types/types.ts
src/strategies/user-auth-strategy.provider.ts

remove bearer and client password passport strategies type declarations export
and export them from root
GH-214
Fixes #214

fix(chore): export mandatory strategies from package 

---

package-lock.json
package.json
src/strategies/SAML/saml-verify.provider.ts
src/strategies/passport/passport-apple-oauth2/apple-auth-strategy-factory-provider.ts
src/strategies/passport/passport-apple-oauth2/apple-auth-verify.provider.ts
src/strategies/passport/passport-azure-ad/azuread-auth-verify.provider.ts
src/strategies/passport/passport-bearer/bearer-strategy-factory-provider.ts
src/strategies/passport/passport-client-password/client-password-strategy-factory-provider.ts
src/strategies/passport/passport-client-password/secure-client-password-strategy-factory-provider.ts
src/strategies/passport/passport-facebook-oauth2/facebook-auth-verify.provider.ts
src/strategies/passport/passport-google-oauth2/google-auth-verify.provider.ts
src/strategies/passport/passport-insta-oauth2/insta-auth-verify.provider.ts
src/strategies/passport/passport-local/local-password-strategy-factory-provider.ts
src/strategies/types/types.ts
src/strategies/user-auth-strategy.provider.ts

BREAKING CHANGE:
YES
Update the lb4 dependencies as lb4 dropped support for node 16 or lower
Fixes #217 

chore(deps): update lb4 dependencies

---

src/providers/user-authentication.provider.ts
src/strategies/SAML/saml-verify.provider.ts
src/strategies/passport/passport-apple-oauth2/apple-auth-strategy-factory-provider.ts
src/strategies/passport/passport-apple-oauth2/apple-auth-verify.provider.ts
src/strategies/passport/passport-azure-ad/azuread-auth-verify.provider.ts
src/strategies/passport/passport-bearer/bearer-strategy-factory-provider.ts
src/strategies/passport/passport-client-password/client-password-strategy-factory-provider.ts
src/strategies/passport/passport-client-password/secure-client-password-strategy-factory-provider.ts
src/strategies/passport/passport-facebook-oauth2/facebook-auth-verify.provider.ts
src/strategies/passport/passport-google-oauth2/google-auth-verify.provider.ts
src/strategies/passport/passport-insta-oauth2/insta-auth-verify.provider.ts
src/strategies/passport/passport-local/local-password-strategy-factory-provider.ts
src/strategies/types/types.ts
src/strategies/user-auth-strategy.provider.ts

BREAKING CHANGE:
Bump major version
Bump major version
Fixes #217 

feat(deps): bump major version

---

README.md

GH-224
Copy the readme to root as well
Fixes #224 

docs(chore): copy the readme to root as well

---

.github/workflows/release.yaml

added changelog step in workflow after release
GH-226
Added the changelog step in release workflow 
Fixes #226 

chore(ci-cd): changelog step

---

.github/workflows/release.yaml

Change the repo reference in release workflow file
Fixes #228

chore(ci-cd):Update release workflow file

---

package-lock.json
package.json

revert sematic-release version update
GH-232
revert sematic-release version update
Fixes #232 

revert(deps): revert sematic-release version update

---

.cz-config.js
docs/README.md

readme file of docs folder updated
update the readme file in docs folder
Fixes # (issue)

chore(docs): update the readme file in docs folder
